/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carnet;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Alodewou Giovanni
 */
public class Acceuil extends javax.swing.JFrame {

    //Statement recevra tout les requetes
    Statement StmtNouveau, StmtListe, StmtRecherche, StmtSupprimer, StmtModifier, StmtCombofill;
    Connexion MaConnexion = new Connexion();

    /**
     * Creates new form NewJFrame
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        softBevelBorder1 = new javax.swing.border.SoftBevelBorder(0);
        BtnSexeGroup = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableContact = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnAjoutContact = new javax.swing.JButton();
        BtnListeContact = new javax.swing.JButton();
        BtnSupprimer = new javax.swing.JButton();
        BtnModifier = new javax.swing.JButton();
        BtnQuitter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTCritereRecherche = new javax.swing.JFormattedTextField();
        BtnRechercher = new javax.swing.JButton();
        CBChampRecherche = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JTNom = new javax.swing.JTextField();
        JTPrenom = new javax.swing.JTextField();
        JTSurnom = new javax.swing.JTextField();
        JTAdresse = new javax.swing.JTextField();
        JTProfession = new javax.swing.JTextField();
        JTNationalite = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JTSiteWeb = new javax.swing.JTextField();
        JTCell = new javax.swing.JFormattedTextField();
        JSDateAnniversaire = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        BtnSexeM = new javax.swing.JRadioButton();
        BtnSexeF = new javax.swing.JRadioButton();
        BtnPremier = new javax.swing.JButton();
        BtnPrecedent = new javax.swing.JButton();
        BtnSuivant = new javax.swing.JButton();
        BtnDernier = new javax.swing.JButton();
        JSAnneeAnniversaire = new javax.swing.JSpinner();
        JTAge = new javax.swing.JFormattedTextField();
        JSMoisAnniversaire = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        JTEmail = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(1, new java.awt.Color(102, 204, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255)), "LISTE DES CONTACTS", 2, 2, new java.awt.Font("Century", 1, 14))); // NOI18N

        TableContact.setAutoCreateRowSorter(true);
        TableContact.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        TableContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableContact.setOpaque(false);
        TableContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableContactMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableContact);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(1, new java.awt.Color(102, 153, 255), new java.awt.Color(102, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        jPanel3.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        BtnAjoutContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/User-Add.png"))); // NOI18N
        BtnAjoutContact.setText("NOUVEAU");
        BtnAjoutContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjoutContactActionPerformed(evt);
            }
        });

        BtnListeContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Command-Refresh.png"))); // NOI18N
        BtnListeContact.setText("ACTUALISER");
        BtnListeContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListeContactActionPerformed(evt);
            }
        });

        BtnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Garbage.png"))); // NOI18N
        BtnSupprimer.setText("SUPPRIMER");
        BtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupprimerActionPerformed(evt);
            }
        });

        BtnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Editor.png"))); // NOI18N
        BtnModifier.setText("MODIFIER");
        BtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifierActionPerformed(evt);
            }
        });

        BtnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Login-Door.png"))); // NOI18N
        BtnQuitter.setText(" QUITTER");
        BtnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnListeContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAjoutContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnQuitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BtnAjoutContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BtnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BtnListeContact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(0, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black, java.awt.Color.lightGray));

        jLabel1.setText("Recherche");
        jLabel1.setOpaque(true);

        JTCritereRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCritereRechercheActionPerformed(evt);
            }
        });
        JTCritereRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTCritereRechercheKeyPressed(evt);
            }
        });

        BtnRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Search-Find.png"))); // NOI18N
        BtnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRechercherActionPerformed(evt);
            }
        });

        CBChampRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nom", "Prenom", "Cell", "Surnom", "Profession", "Evenement", "Email" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CBChampRecherche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JTCritereRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBChampRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTCritereRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMATIONS SUR LE CONTACT...", 1, 3, new java.awt.Font("Century Schoolbook", 1, 12))); // NOI18N

        jLabel2.setText("NOM");

        jLabel3.setText("PRENOM");

        jLabel4.setText("CELL");

        jLabel5.setText("SURNOM");

        jLabel6.setText("AGE");

        jLabel7.setText("NATIONALITE");

        jLabel8.setText("PROFESSION");

        jLabel9.setText("ADRESSE");

        jLabel10.setText("EMAIL");

        jLabel11.setText("ANNIVERSAIRE");

        JTProfession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTProfessionActionPerformed(evt);
            }
        });

        jLabel12.setText("SITE WEB");

        JTSiteWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTSiteWebActionPerformed(evt);
            }
        });

        JTCell.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        JTCell.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        JTCell.setToolTipText("Champ Obligatoire");

        JSDateAnniversaire.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel13.setText("SEXE");

        BtnSexeGroup.add(BtnSexeM);
        BtnSexeM.setText("M");
        BtnSexeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSexeMActionPerformed(evt);
            }
        });

        BtnSexeGroup.add(BtnSexeF);
        BtnSexeF.setText("F");

        BtnPremier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Media-Rewind.png"))); // NOI18N
        BtnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPremierActionPerformed(evt);
            }
        });

        BtnPrecedent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Previous.png"))); // NOI18N
        BtnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrecedentActionPerformed(evt);
            }
        });

        BtnSuivant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Navigation-Right.png"))); // NOI18N
        BtnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuivantActionPerformed(evt);
            }
        });

        BtnDernier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/Media-Fast-Forward.png"))); // NOI18N
        BtnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDernierActionPerformed(evt);
            }
        });

        JSAnneeAnniversaire.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2999, 1));

        JTAge.setEditable(false);

        JSMoisAnniversaire.setMaximumRowCount(11);
        JSMoisAnniversaire.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Decembre", " " }));
        JSMoisAnniversaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSMoisAnniversaireActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        jLabel14.setToolTipText(JTCell.getToolTipText());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTAdresse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTProfession, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTSurnom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTNationalite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTSiteWeb)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JTCell)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JTEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnSexeM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(BtnSexeF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JTAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(96, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnPrecedent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BtnDernier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JSDateAnniversaire, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JSMoisAnniversaire, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JSAnneeAnniversaire, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(BtnSexeM)
                    .addComponent(BtnSexeF))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTSurnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JTProfession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JTAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(JTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JSDateAnniversaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSAnneeAnniversaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSMoisAnniversaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JTSiteWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSuivant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnPrecedent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDernier, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );

        jToolBar1.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar1.setRollover(true);

        jMenu4.setText("Contacts");
        jMenu4.setToolTipText("");
        jMenu4.setComponentPopupMenu(jPopupMenu1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setBackground(new java.awt.Color(102, 102, 102));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/minim/User-Add.png"))); // NOI18N
        jMenuItem2.setText("Nouveau...   ");
        jMenuItem2.setToolTipText("Creer Nouveau contact");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);
        jMenu4.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/minim/Garbage.png"))); // NOI18N
        jMenuItem3.setText("Supprimer...   ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);
        jMenu4.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/minim/Search-Find.png"))); // NOI18N
        jMenuItem4.setText("Rechercher...   ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);
        jMenu4.add(jSeparator3);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/minim/Logout.png"))); // NOI18N
        jMenuItem5.setText("Quitter");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar2.add(jMenu4);

        jMenu1.setText(" Outils");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Acceuil/minim/Command-Refresh.png"))); // NOI18N
        jMenuItem1.setText(" Liste des Contacts");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void BtnAjoutContactActionPerformed(java.awt.event.ActionEvent evt) {                                                

        FenetreAjoutContact AppelFenetre = new FenetreAjoutContact();
        AppelFenetre.setVisible(true);

// TODO add your handling code here:
    }                                               

    private void BtnListeContactActionPerformed(java.awt.event.ActionEvent evt) {                                                

        Model.setRowCount(0);

        RequeteListe = "SELECT *From Personne order by Nom ASC";
        try {
            StmtListe = MaConnexion.ObtenirConnexion().createStatement();
            ResultSet Resultat = StmtListe.executeQuery(RequeteListe);
            while (Resultat.next()) {
                Model.addRow(new Object[]{Resultat.getString("Nom"), Resultat.getString("Prenom"), Resultat.getString("Sexe"), Resultat.getString("Cell"), Resultat.getString("Surnom"), Resultat.getString("Age"), Resultat.getString("Nationalite"), Resultat.getString("Profession"), Resultat.getString("Adresse"), Resultat.getString("Email"), Resultat.getString("Anniversaire"), Resultat.getString("SiteWeb")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erreur de chargement de la liste des contacts" + ex.getMessage());
            System.out.println("Requete de la liste  " + ex);
        }
        TableContact.setModel(Model);

// TODO add your handling code here:
    }                                               

    private void JTProfessionActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void JTSiteWebActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {                                             

        int ChoixQuitter = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment supprimer ce contact ?", "Confirmation", 0, 2);

        switch (ChoixQuitter) {
            case 0:
                
                String SuppCell = JTCell.getText();
        RequeteSupprimer = "DELETE from Personne Where Cell = '" + SuppCell + "'  ";
        try {
            StmtSupprimer = MaConnexion.ObtenirConnexion().createStatement();
            StmtSupprimer.executeUpdate(RequeteSupprimer);

            JOptionPane.showMessageDialog(null, "Suppresion Effectuée avec succces");
            ViderChamp();
            BtnListeContactActionPerformed(evt);
            
        } catch (SQLException ex) {
            System.out.println("Echec Suppression " + ex.getMessage());
        }
                
            case 1:
                  return;
        }
        
       
        


    }                                            

    private void BtnSexeMActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    //PREMIER
    private void BtnPremierActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            ViderChamp();
            i = 0;
            Remplir(i);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Premier Contact Atteint  " + ex.getMessage());
        }
    }                                          

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  

        CreationTable();
        System.out.println("Table crée");
        ViderChamp();
        System.out.println("Champs vidés ");
        BtnListeContact.doClick();
        System.out.println("Liste crée");
        i = 0;
        Remplir(i);
        System.out.println("Table crée");
    }                                 

    private void JSMoisAnniversaireActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  
    //PRECEDENT
    private void BtnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try {
            ViderChamp();
            Remplir(--i);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur Affichage Precedent  " + ex.getMessage());
        }

    }                                            
    //SUIVANT
    private void BtnSuivantActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            ViderChamp();
            Remplir(i++);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erreur Affichage Suivant  " + ex.getMessage());
        }
    }                                          
    //DERNIER
    private void BtnDernierActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            i = (Model.getRowCount()) - 1;
            Remplir(i);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Dernier contact atteint  " + ex.getMessage());
        }
    }                                          

    private void TableContactMouseClicked(java.awt.event.MouseEvent evt) {                                          

        try {
            i = TableContact.getSelectedRow();
            Remplir(i);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Erreur  de selection contact  " + ex.getMessage());
        }
    }                                         

    private void BtnModifierActionPerformed(java.awt.event.ActionEvent evt) {                                            

        //Control du sexe
        if (BtnSexeM.isSelected()) {
            Sexe = 'M';
        } else if (BtnSexeF.isSelected()) {
            Sexe = 'F';
        }
        // fin

        //controle de L'age
        String TypeDate = "yyyy";
        Date LaDate = new Date();
        SimpleDateFormat MaDate = new SimpleDateFormat(TypeDate);
        String DateModifie = MaDate.format(LaDate);
        if ((Integer.parseInt(JSAnneeAnniversaire.getValue().toString())) == 1950) {
            Age = "";
        } else {
            Age = String.valueOf((Integer.parseInt(DateModifie)) - (Integer.parseInt(JSAnneeAnniversaire.getValue().toString())));

        }
                //fin

        //Controle de la date de l'anniversaire
        if (((Integer.parseInt(JSAnneeAnniversaire.getValue().toString())) == 1950) && (JSMoisAnniversaire.getSelectedIndex() == 0) && (Integer.parseInt(JSDateAnniversaire.getValue().toString()) == 1)) {
            Anniversaire = "";
        } else {

            Anniversaire = JSAnneeAnniversaire.getValue().toString() + "-" + String.valueOf(JSMoisAnniversaire.getSelectedIndex() + 1) + "-" + JSDateAnniversaire.getValue().toString();

        }
    //fin

        // COntrole du numero de telephone
        try {

            if (!"".equals(JTCell.getText().trim())) {

                Cell = Integer.parseInt(JTCell.getText().trim());
            } else if ("".equals(JTCell.getText().trim())) {

                JOptionPane.showMessageDialog(null, "Veuillez saisir un numero");
                return;
            }

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Le Numero est saisi est incorrect");
            return;

        }

        //Fin
        // CONTROLE DE L'EMAIL
        //Controle de l'email
        if ((JTEmail.getText().trim().isEmpty())) {
            Email = "";
        } else if ((JTEmail.getText().trim() != "") && ((JTEmail.getText().contains("."))) && ((JTEmail.getText().contains("@")))) {
            Email = (JTEmail.getText());

        } else {
            JOptionPane.showMessageDialog(null, " Format Email non respecte , Username@domain.com");
            return;

        }
        //Fin

        //FIN
        Nom = JTNom.getText();
        Prenom = JTPrenom.getText();
        Surnom = JTSurnom.getText();
        Nationalite = JTNationalite.getText();
        Profession = JTProfession.getText();
        Adresse = JTAdresse.getText();

        SiteWeb = JTSiteWeb.getText();

        RequeteModifier = "UPDATE Personne SET Nom = '" + Nom + "' , Prenom = '" + Prenom + "' , Sexe =  '" + Sexe + "' , Cell ='" + Cell + "', Surnom =  '" + Surnom + "' , Age =  '" + Age + "' , Nationalite = '" + Nationalite + "' , Profession =  '" + Profession + "' , Adresse = '" + Adresse + "' , Email =  '" + Email + "' , Anniversaire = '" + Anniversaire + "' , SiteWeb = '" + SiteWeb + "' Where Cell = '" + (Cell) + "' ";
        //RequeteModifier = "INSERT INTO Personne(Nom, Prenom, Sexe, Cell, Surnom, Age, Nationalite, Profession, Adresse, Email, Anniversaire, SiteWeb) VALUES ('" + Nom + "' , '" + Prenom + "' , '" + Sexe + "', '" + Cell + "' , '" + Surnom + "' , '" + Age + "' , '" + Nationalite + "' , '" + Profession + "' , '" + Adresse + "' , '" + Email + "' , '" + Anniversaire + "' , '" + SiteWeb + "') ON DUPLICATE KEY UPDATE(Nom='"+Nom+"', Prenom='"+Prenom+"', Sexe='"+Sexe+"', Surnom='"+Surnom+"', Age='"+Age+"', Nationalite='"+Nationalite+"', Profession='"+Profession+"', Adresse='"+Adresse+"', Email='"+Email+"', Anniversaire='"+Anniversaire+"', SiteWeb='"+SiteWeb+"')";// VALUES ( , '"+Prenom+"' , '"+Sexe+"', '"+Surnom+"' , '"+Age+"' , '"+Nationalite+"' , '"+Profession+"' , '"+Adresse+"' , '"+Email+"' , '"+Anniversaire+"' , '"+SiteWeb+"') ";    

        try {
            StmtNouveau = MaConnexion.ObtenirConnexion().createStatement();
            //StmtNouveau.executeQuery(RequeteModifier);
            StmtNouveau.executeUpdate(RequeteModifier);
            JOptionPane.showMessageDialog(null, " Contact Modifié avec succes");

            //Pour reinitialiserles champs a la fin de l'enregistrement
            ViderChamp();

            //Pour Actualiser la liste a la fin de l'enregistrement
            BtnListeContact.doClick();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Echec de la Modification " + ex.getMessage());
            System.out.println(ex);

        }
    }                                           

    private void BtnRechercherActionPerformed(java.awt.event.ActionEvent evt) {                                              

        Model.setRowCount(0);
        String Critere = JTCritereRecherche.getText();
        String Champ = CBChampRecherche.getSelectedItem().toString();
        RequeteRecherche = " Select * From personne where " + Champ + " like '%" + Critere + "%' order by " + Champ + " asc ";

        try {
            StmtRecherche = MaConnexion.ObtenirConnexion().createStatement();
            ResultSet ResultatRech = StmtRecherche.executeQuery(RequeteRecherche);
            /* ResultatRech.last();
             int NbrRow = ResultatRech.getRow();*/
            while (ResultatRech.next()) {
                Model.addRow(new Object[]{ResultatRech.getString("Nom"), ResultatRech.getString("Prenom"), ResultatRech.getString("Sexe"), ResultatRech.getString("Cell"), ResultatRech.getString("Surnom"), ResultatRech.getString("Age"), ResultatRech.getString("Nationalite"), ResultatRech.getString("Profession"), ResultatRech.getString("Adresse"), ResultatRech.getString("Email"), ResultatRech.getString("Anniversaire"), ResultatRech.getString("SiteWeb")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erreur de chargement de la liste des contacts" + ex.getMessage());
            System.out.println("Requete de la Recherche  " + ex);
        }
        TableContact.setModel(Model);


    }                                             

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        BtnAjoutContactActionPerformed(evt);
    }                                          

    private void JTCritereRechercheKeyPressed(java.awt.event.KeyEvent evt) {                                              
        Model.setRowCount(0);
        String Critere = JTCritereRecherche.getText();
        String Champ = CBChampRecherche.getSelectedItem().toString();
        RequeteRecherche = " Select * From personne where " + Champ + " like '%" + Critere + "%' order by " + Champ + " asc ";

        try {
            StmtRecherche = MaConnexion.ObtenirConnexion().createStatement();
            ResultSet ResultatRech = StmtRecherche.executeQuery(RequeteRecherche);
            /* ResultatRech.last();
             int NbrRow = ResultatRech.getRow();*/
            while (ResultatRech.next()) {
                Model.addRow(new Object[]{ResultatRech.getString("Nom"), ResultatRech.getString("Prenom"), ResultatRech.getString("Sexe"), ResultatRech.getString("Cell"), ResultatRech.getString("Surnom"), ResultatRech.getString("Age"), ResultatRech.getString("Nationalite"), ResultatRech.getString("Profession"), ResultatRech.getString("Adresse"), ResultatRech.getString("Email"), ResultatRech.getString("Anniversaire"), ResultatRech.getString("SiteWeb")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erreur de chargement de la liste des contacts" + ex.getMessage());
            System.out.println("Requete de la Recherche  " + ex);
        }
        TableContact.setModel(Model);
    }                                             

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        BtnSupprimerActionPerformed(evt);       // TODO add your handling code here:
    }                                          

    private void JTCritereRechercheActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           

        JTCritereRecherche.grabFocus();

    }                                          

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        BtnListeContactActionPerformed(evt);
    }                                          

    private void BtnQuitterActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //"Voulez vous vraiment quitter ?", "Confirmation"
        int ChoixQuitter = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment quitter ?", "Confirmation", 0, 2);

        switch (ChoixQuitter) {
            case 0:
                System.exit(0);
            case 1:

        }

    }                                          

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        BtnQuitterActionPerformed(evt);
    }                                          

    public void Remplir(int i) {

        ViderChamp();
        try {

            if (i == 0) {
                BtnPrecedent.setEnabled(false);
                BtnSuivant.setEnabled(true);
                BtnPremier.setEnabled(false);
                BtnDernier.setEnabled(true);
            } else if (i == (Model.getRowCount() - 1)) {
                BtnPrecedent.setEnabled(true);
                BtnSuivant.setEnabled(false);
                BtnDernier.setEnabled(false);
                BtnPremier.setEnabled(true);
            } else {
                BtnPrecedent.setEnabled(true);
                BtnSuivant.setEnabled(true);
                BtnPremier.setEnabled(true);
                BtnDernier.setEnabled(true);
            }

            if (!"".equals((Model.getValueAt(i, 0)).toString())) {
                JTNom.setText(Model.getValueAt(i, 0).toString());
            }
            if (!"".equals((Model.getValueAt(i, 1)).toString())) {
                JTPrenom.setText(Model.getValueAt(i, 1).toString());
            }

            //Sexe
            if ("M".equals(Model.getValueAt(i, 2).toString())) {
                BtnSexeM.setSelected(true);
            } else if ("F".equals(Model.getValueAt(i, 2))) {
                BtnSexeF.setSelected(true);
            } else {
                BtnSexeGroup.clearSelection();
            }//finSexe

            JTCell.setText(Model.getValueAt(i, 3).toString());

            if (!"".equals((Model.getValueAt(i, 4)).toString())) {
                JTSurnom.setText(Model.getValueAt(i, 4).toString());
            }

            if (!"".equals((Model.getValueAt(i, 5)).toString())) {
                JTAge.setText(Model.getValueAt(i, 5).toString());
            }

            if (!"".equals((Model.getValueAt(i, 6)).toString())) {
                JTNationalite.setText(Model.getValueAt(i, 6).toString());
            }
            if (!"".equals((Model.getValueAt(i, 7)).toString())) {
                JTProfession.setText(Model.getValueAt(i, 7).toString());
            }
            if (!"".equals((Model.getValueAt(i, 8)).toString())) {
                JTAdresse.setText(Model.getValueAt(i, 8).toString());
            }
            if (!"".equals((Model.getValueAt(i, 9)).toString())) {
                JTEmail.setText(Model.getValueAt(i, 9).toString());
            }

            //ANNIV
            String DeLaBase = Model.getValueAt(i, 10).toString();
            String[] LaDate = {"", "", ""};
            if (!"".equals(DeLaBase)) {
                LaDate = DeLaBase.split("-", 3);

                JSDateAnniversaire.setEnabled(true);
                JSMoisAnniversaire.setEnabled(true);
                JSAnneeAnniversaire.setEnabled(true);

                JSDateAnniversaire.setValue(Integer.parseInt(LaDate[2]));
                JSMoisAnniversaire.setSelectedIndex((Integer.parseInt(LaDate[1])) - (1));
                JSAnneeAnniversaire.setValue(Integer.parseInt(LaDate[0]));
            } else {
                JSDateAnniversaire.setValue(0);
                JSMoisAnniversaire.setSelectedIndex(12);
                JSAnneeAnniversaire.setValue(1950);
            }

            if (!"".equals((Model.getValueAt(i, 11)).toString())) {
                JTSiteWeb.setText(Model.getValueAt(i, 11).toString());
            }

        } catch (NumberFormatException ex) {
            System.out.println(ex + ex.getMessage());

        }

    }

    public void CreationTable() {
        Model.addColumn("Nom ");
        Model.addColumn("Prenom");
        Model.addColumn("Sexe");
        Model.addColumn("Numero");
        Model.addColumn("Surnom");
        Model.addColumn("Age");
        Model.addColumn("Nationalite");
        Model.addColumn("Profession");
        Model.addColumn("Adresse");
        Model.addColumn("Email");
        Model.addColumn("Anniversaire");
        Model.addColumn("SiteWeb");
    }

    public void ViderChamp() {
        JTNom.setText("");
        JTPrenom.setText("");
        BtnSexeGroup.clearSelection();
        JTCell.setValue(null);
        JTSurnom.setText("");
        JTAge.setValue("");
        JTNationalite.setText("");
        JTProfession.setText("");
        JTAdresse.setText("");
        JTEmail.setText("");
        JSDateAnniversaire.setValue(1);
        JSMoisAnniversaire.setSelectedIndex(0);
        JSAnneeAnniversaire.setValue(1950);
        JTSiteWeb.setText("");
    }
    /*  private void Fillcombo(){
     // TODO add your handling code here:
     Connection ConCombo = MaConnexion.ObtenirConnexion();
     String RequeteCombo =("select * from personne") ;
     try {
     PreparedStatement StmtCombo  = ConCombo.prepareStatement(RequeteCombo);
     ResultSet rs;
     rs = StmtCombo.executeQuery();
     while (rs.next()) {
              
     String lastName = rs.getString("name");
     rs.get
     //System.out.println(lastName + "\n");
     // System.out.println(pst);
     cmbname.addItem(lastName);
     //cmbname.getModel();
     }
     }
     catch (Exception ex) {
     System.out.print(ex);
     }
     }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Mes Variables
    String Nom, Prenom, Surnom, Age, Nationalite, Profession, Adresse, Email, Anniversaire, SiteWeb;
    char Sexe;
    int Cell, i;
    String RequeteNouveau, RequeteModifier, RequeteRecherche, RequeteSupprimer, RequeteListe;
    DefaultTableModel Model = new DefaultTableModel();


    // Variables declaration - do not modify                     
    private javax.swing.JButton BtnAjoutContact;
    private javax.swing.JButton BtnDernier;
    public static javax.swing.JButton BtnListeContact;
    private javax.swing.JButton BtnModifier;
    private javax.swing.JButton BtnPrecedent;
    private javax.swing.JButton BtnPremier;
    public static javax.swing.JButton BtnQuitter;
    private javax.swing.JButton BtnRechercher;
    private javax.swing.JRadioButton BtnSexeF;
    private javax.swing.ButtonGroup BtnSexeGroup;
    private javax.swing.JRadioButton BtnSexeM;
    private javax.swing.JButton BtnSuivant;
    private javax.swing.JButton BtnSupprimer;
    private javax.swing.JComboBox CBChampRecherche;
    private javax.swing.JSpinner JSAnneeAnniversaire;
    private javax.swing.JSpinner JSDateAnniversaire;
    private javax.swing.JComboBox JSMoisAnniversaire;
    private javax.swing.JTextField JTAdresse;
    private javax.swing.JFormattedTextField JTAge;
    private javax.swing.JFormattedTextField JTCell;
    private javax.swing.JFormattedTextField JTCritereRecherche;
    private javax.swing.JTextField JTEmail;
    private javax.swing.JTextField JTNationalite;
    private javax.swing.JTextField JTNom;
    private javax.swing.JTextField JTPrenom;
    private javax.swing.JTextField JTProfession;
    private javax.swing.JTextField JTSiteWeb;
    private javax.swing.JTextField JTSurnom;
    private javax.swing.JTable TableContact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.border.SoftBevelBorder softBevelBorder1;
    // End of variables declaration                   
}
